import { useState, useEffect } from 'react'
import {
  AreaChart, Area, BarChart, Bar, LineChart, Line, XAxis, YAxis,
  CartesianGrid, Tooltip, Legend, ResponsiveContainer, Cell,
} from 'recharts'
import HeroSection     from '../components/HeroSection'
import PortfolioFooter from '../components/PortfolioFooter'
import BusinessCta     from '../components/BusinessCta'
import { useLang }     from '../contexts/LangContext'

/*  Analisis de registros de seguridad.
 *
 *  Los JSON de /data/logs/ salen de log_analysis.py, el mismo modulo que
 *  genera el informe en Markdown del repositorio: analyze() cuenta una vez y
 *  de ahi salen las dos cosas. Antes contar y dar formato vivian juntos, y la
 *  unica forma de sacar estos numeros habria sido volver a leer el log por
 *  nuestra cuenta, con lo que el panel y el informe podrian acabar diciendo
 *  cosas distintas del mismo fichero.
 */

const REPO = 'https://github.com/mindset-code/project-security-log-analysis'
const VERDE = '#6fae8c'
const AZUL  = '#7ea6d4'
const ORO   = '#d0a458'
const ROJO  = '#c9756b'
const TENUE = '#a9b6c5'
const REJILLA = '#22303f'

// El color dice si el evento es rutina o es una amenaza; el orden, cuanto pesa.
const COLOR_EVENTO = {
  LOGIN_SUCCESS: VERDE,
  LOGIN_FAILED: ORO,
  BRUTE_FORCE_ATTEMPT: ROJO,
  ACCESS_DENIED: '#b98fb5',
  PORT_SCAN_DETECTED: AZUL,
}

const FICHEROS = ['resumen', 'eventos', 'top_ips', 'top_fallidos', 'por_hora', 'por_dia']

const CAJA = { background: '#101722', border: '1px solid #2c3d50', borderRadius: 8 }
const leyenda = v => <span style={{ color: TENUE, fontSize: 11 }}>{v}</span>

const T = {
  es: {
    badge: 'Seguridad',
    title: 'Análisis de registros',
    description:
      'Cinco mil líneas de registro de una semana, convertidas en la lista corta de direcciones que conviene bloquear. Es lo primero que hace un centro de operaciones de seguridad: contar, ordenar y separar el ruido del intento de entrada. El mismo módulo produce este panel y el informe en Markdown del repositorio, así que no pueden contradecirse.',
    stats: ['Líneas analizadas', 'Direcciones', 'Eventos de amenaza', 'Fuerza bruta'],
    cargando: 'Analizando el registro…',
    error: 'No se ha podido cargar el análisis',
    eventos: 'Qué hay en el registro',
    eventosDesc: 'Recuento por tipo de evento sobre las 5.000 líneas',
    hora: 'A qué hora ocurre cada cosa',
    horaDesc: 'Eventos por hora del día, acumulando los siete días',
    dia: 'Volumen por día',
    diaDesc: 'Total de eventos registrados cada día',
    fallidos: 'Las direcciones que conviene mirar',
    fallidosDesc: 'Intentos de acceso fallidos por dirección, las cinco primeras',
    concentracion: dato =>
      `Cinco direcciones de ${dato.ips} concentran ${dato.suma} de los ${dato.total} intentos fallidos (${dato.pct} %). Una dirección corriente de esta red acumula menos de diez. Esa diferencia es la lista de bloqueo.`,
    lectura: 'Los intentos fallidos, los escaneos de puertos y la fuerza bruta se agrupan de madrugada, cuando no hay nadie mirando; los accesos correctos siguen el horario de oficina. Un pico nocturno en esta gráfica es el motivo por el que se revisa.',
    intentos: 'intentos',
    eventosLbl: 'eventos',
    footerCtx: 'Registros sintéticos generados por el propio repositorio: no hay datos de ninguna red real · Python (biblioteca estándar) · React + Recharts ·',
  },
  en: {
    badge: 'Security',
    title: 'Security log analysis',
    description:
      'Five thousand log lines from one week, turned into the short list of addresses worth blocking. It is the first thing a security operations centre does: count, rank and separate the noise from the break-in attempt. The same module produces this dashboard and the repository Markdown report, so the two cannot disagree.',
    stats: ['Lines analysed', 'Addresses', 'Threat events', 'Brute force'],
    cargando: 'Analysing the log…',
    error: 'Could not load the analysis',
    eventos: 'What is in the log',
    eventosDesc: 'Count per event type across the 5,000 lines',
    hora: 'When each thing happens',
    horaDesc: 'Events per hour of day, across all seven days',
    dia: 'Volume per day',
    diaDesc: 'Total events recorded each day',
    fallidos: 'The addresses worth a look',
    fallidosDesc: 'Failed login attempts per address, top five',
    concentracion: dato =>
      `Five addresses out of ${dato.ips} account for ${dato.suma} of the ${dato.total} failed attempts (${dato.pct} %). An ordinary host on this network racks up fewer than ten. That gap is the block list.`,
    lectura: 'Failed logins, port scans and brute force cluster in the small hours, when nobody is watching; successful logins follow office hours. A night-time spike on this chart is the reason you look.',
    intentos: 'attempts',
    eventosLbl: 'events',
    footerCtx: 'Synthetic logs generated by the repository itself: no data from any real network · Python (standard library) · React + Recharts ·',
  },
}

export default function LogsDashboard() {
  const [datos, setDatos] = useState(null)
  const [error, setError] = useState(null)
  const { lang } = useLang()
  const t = T[lang]

  useEffect(() => {
    Promise.all(
      FICHEROS.map(f =>
        fetch(`/data/logs/${f}.json`).then(r => {
          if (!r.ok) throw new Error(`${f}: ${r.status}`)
          return r.json()
        }).then(d => [f, d])
      )
    )
      .then(r => setDatos(Object.fromEntries(r)))
      .catch(e => setError(e.message))
  }, [])

  if (error) return <div className="error">{t.error}: {error}</div>
  if (!datos) return <div className="loading">{t.cargando}</div>

  const r = datos.resumen
  const num = n => n.toLocaleString(lang === 'es' ? 'es-ES' : 'en-US')

  // Lo que hace util al ranking no es el orden, es la distancia: se calcula
  // aqui y se dice con numeros, en vez de dejar que el lector estime a ojo
  // cinco barras parecidas entre si.
  const suma = datos.top_fallidos.reduce((a, x) => a + x.conteo, 0)
  const concentracion = {
    ips: num(r.ips),
    suma: num(suma),
    total: num(r.fallidos),
    pct: ((suma * 100) / r.fallidos).toFixed(1),
  }

  const context = (
    <>
      {t.footerCtx}{' '}
      <a href={REPO} target="_blank" rel="noreferrer">project-security-log-analysis</a>
    </>
  )

  return (
    <div className="dashboard">
      <HeroSection
        badge={t.badge}
        badgeColor={ROJO}
        title={t.title}
        description={t.description}
        stats={[
          { value: num(r.analizadas), label: t.stats[0] },
          { value: num(r.ips), label: t.stats[1] },
          { value: num(r.amenazas), label: t.stats[2] },
          { value: num(r.fuerza_bruta), label: t.stats[3] },
        ]}
        techs={['Python', 'Regex', 'Counter', 'React', 'Recharts', 'SOC']}
        githubUrl={REPO}
      />

      <main>
        <div className="grid grid-1">
          <div className="card">
            <h2>{t.hora}</h2>
            <p className="card-desc">{t.horaDesc}</p>
            <ResponsiveContainer width="100%" height={300}>
              <AreaChart data={datos.por_hora} margin={{ top: 8, right: 8, bottom: 4, left: 8 }}>
                <CartesianGrid stroke={REJILLA} vertical={false} />
                <XAxis dataKey="hora" stroke={TENUE} fontSize={11} interval={1} />
                <YAxis stroke={TENUE} fontSize={12} />
                <Tooltip contentStyle={CAJA} />
                <Legend formatter={leyenda} />
                {r.tipos.map(tipo => (
                  <Area
                    key={tipo}
                    type="monotone"
                    dataKey={tipo}
                    stackId="1"
                    stroke={COLOR_EVENTO[tipo]}
                    fill={COLOR_EVENTO[tipo]}
                    fillOpacity={0.55}
                  />
                ))}
              </AreaChart>
            </ResponsiveContainer>
            <p className="card-desc" style={{ marginTop: '0.6rem' }}>{t.lectura}</p>
          </div>
        </div>

        <div className="grid grid-2">
          <div className="card">
            <h2>{t.eventos}</h2>
            <p className="card-desc">{t.eventosDesc}</p>
            <ResponsiveContainer width="100%" height={260}>
              <BarChart data={datos.eventos} layout="vertical" margin={{ top: 8, right: 24, bottom: 4, left: 8 }}>
                <CartesianGrid stroke={REJILLA} horizontal={false} />
                <XAxis type="number" stroke={TENUE} fontSize={12} />
                {/* Los nombres de evento son largos y con guion bajo; sin un
                    ancho generoso recharts los parte por la mitad. */}
                <YAxis type="category" dataKey="evento" stroke={TENUE} fontSize={10} width={150} />
                <Tooltip contentStyle={CAJA} formatter={v => [num(v), t.eventosLbl]} />
                <Bar dataKey="conteo" radius={[0, 3, 3, 0]}>
                  {datos.eventos.map(e => (
                    <Cell key={e.evento} fill={COLOR_EVENTO[e.evento] ?? TENUE} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>

          <div className="card">
            <h2>{t.dia}</h2>
            <p className="card-desc">{t.diaDesc}</p>
            <ResponsiveContainer width="100%" height={260}>
              {/* Margen derecho generoso: el ultimo punto cae pegado al borde
                  y su fecha se cortaba por la mitad -- «01-1» en vez de
                  «01-11»-- que es justo el dia mas reciente, el que primero
                  se mira. */}
              <LineChart data={datos.por_dia} margin={{ top: 8, right: 26, bottom: 4, left: 8 }}>
                <CartesianGrid stroke={REJILLA} vertical={false} />
                <XAxis dataKey="dia" stroke={TENUE} fontSize={10} interval={0} tickFormatter={v => v.slice(5)} />
                <YAxis stroke={TENUE} fontSize={12} domain={[0, 'dataMax + 100']} />
                <Tooltip contentStyle={CAJA} formatter={v => [num(v), t.eventosLbl]} />
                <Line type="monotone" dataKey="conteo" stroke={AZUL} strokeWidth={2} dot={{ r: 3 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="grid grid-1">
          <div className="card">
            <h2>{t.fallidos}</h2>
            <p className="card-desc">{t.fallidosDesc}</p>
            <ResponsiveContainer width="100%" height={240}>
              <BarChart data={datos.top_fallidos} layout="vertical" margin={{ top: 8, right: 24, bottom: 4, left: 8 }}>
                <CartesianGrid stroke={REJILLA} horizontal={false} />
                <XAxis type="number" stroke={TENUE} fontSize={12} />
                <YAxis type="category" dataKey="ip" stroke={TENUE} fontSize={11} width={112} />
                <Tooltip contentStyle={CAJA} formatter={v => [num(v), t.intentos]} />
                <Bar dataKey="conteo" fill={ROJO} radius={[0, 3, 3, 0]} />
              </BarChart>
            </ResponsiveContainer>
            <p className="card-desc" style={{ marginTop: '0.6rem', color: ORO }}>
              {t.concentracion(concentracion)}
            </p>
          </div>
        </div>
      </main>

      <BusinessCta service="ia-automatizacion" />
      <PortfolioFooter context={context} />
    </div>
  )
}
